version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: passiv
      POSTGRES_USER: passiv_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - backend
      - redis
    command: bash ./celery_worker.sh

  frontend:
    build:
      context: ./passiv-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./passiv-frontend:/app
    stdin_open: true
    tty: true

volumes:
  postgres_data:
