version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: passiv
      POSTGRES_USER: passiv
      POSTGRES_PASSWORD: passiv
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "passiv"]
      interval: 5s
      retries: 5

volumes:
  pg_data:
