# Generated by Django 5.1.7 on 2025-03-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.CharField(max_length=255)),
                ("version", models.IntegerField()),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.TextField(blank=True)),
                ("metrics", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("content_id", "version")},
            },
        ),
    ]
