# Generated by Django 4.2.20 on 2025-04-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
        ('investment', '0003_investmentopportunity_source_type'),
        ('content', '0002_contentversion_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='crypto_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='crypto.cryptoasset'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='investment.investmentopportunity'),
        ),
    ]
