# Generated by Django 4.2.20 on 2025-04-23 19:41

from django.db import migrations, models

def backfill_titles(apps, schema_editor):
    ContentVersion = apps.get_model("content", "ContentVersion")
    for cv in ContentVersion.objects.filter(title=""):
        if cv.opportunity_id:
            cv.title = f"{cv.opportunity.ticker}: {cv.opportunity.opportunity_name} Snapshot"
        elif cv.crypto_asset_id:
            cv.title = f"{cv.crypto_asset.symbol} Pulse Check"
        else:
            cv.title = "Quick Take"
        cv.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentversion_crypto_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_titles, migrations.RunPython.noop),
    ]
