FROM node:20

WORKDIR /app

# Copy only package files and install dependencies
COPY package*.json ./

RUN npm install

# Then copy the rest of your frontend source
COPY . .

# Start dev server using local vite
CMD ["npm", "run", "dev"]
