# .github/workflows/ci.yml
name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: passiv
          POSTGRES_USER: passiv_user
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd="pg_isready -U passiv_user"
          --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python manage.py migrate
      - run: pytest
      - run: pip install bandit pip-audit
      - run: bandit -q -r .
      - run: pip-audit -n
